import random

try:
    for i in range (1,4): # The programme ought to allow the user three attempts of guessing the random number
        while (i < 4): # for as long at the attempts is not the 3rd chance, the user must be allowed more chances
            random_number = random.randint(0,10) #the programme must generate 3 random numbers
            print("Random Number:\n"+ str(random_number))# The random numbers must be printed out for the programmer to see but the user must still guess
            input_guess = int (input("Enter your guessed number:")) # The guessed number should be converted to be an integer
        if random_number == input_guess: #if the guessed number is equal to the random number generated by the programme, the output must be 'Correct'
            print("Correct!")
        elif random_number != input_guess: #However, if the guessed_no. is different from the random number, the output should be 'Incorrect'
            print("Incorrect!")
        else:
            print("Time Out!") # More than three attempts must return 'Time Out!' BUT I DON'T THINK THAT THIS PART IS WORKING...
        break
except ValueError:
    print("Oops! Your entry is in wrong format")

